# GhostLock kernel profile: 6.1.25-android14-11-maybe-dirty (HOCON).
include "credential-6x.conf"
include "kernelsnitch-6x.conf"
release = "6.1.25-android14-11-maybe-dirty"
schema_version = 1
kernel_major = 6
recommend_shizuku = 0
kernel_phys_load = 2818572288
kernel_phys_offset = null
route {
  tcp_zerocopy {
    compact_waiter = 1
  }
}
fallback {
  to = "none"
}
kernelsnitch {
  mm_struct_sz = 1024
}
task_struct {
  prio = 132
  normal_prio = 140
  sched_task_group = 840
  pi_lock = 2340
  pi_waiters = 2360
  pi_top_task = 2376
  pi_blocked_on = 2384
  pid = 1584
  tgid = 1588
  atomic_flags = 1520
  real_cred = 2096
  cred = 2104
  comm = 2120
  tasks = 1360
  seccomp = 2304
}
offset {
  empty_zero_page = null
  init_task = 32042496
  init_cred = 32123184
  root_task_group = 33945024
  selinux_enforcing = 34281928
  selinux_blob_sizes = 21707280
  security_hook_heads = 21705488
  slide_nfulnl_logger = 31992360
  slide_boot_id = 34416808
  slide_loggers_0_1 = 31992176
}
